version: '1'
rules:
    - base: master
      upstream: Onlineberatung:master
      mergeMethod: squash
    - base: develop
      upstream: Onlineberatung:develop
      mergeMethod: squash
label: ':arrow_heading_down: pull'
conflictLabel: 'merge-conflict'
