name: Publish tagged versions to npm package

on:
    push:
        tags:
            - 'npmPackage.v.*'

jobs:
    build:
        name: Build
        if: "!contains(github.event.head_commit.author, 'action@github.com')"
        runs-on: ubuntu-latest
        steps:
            - name: Get the tag version
              run: echo VERSION=$(echo -n "${GITHUB_REF/refs\/tags\//}") >> $GITHUB_ENV
            - uses: actions/checkout@v2.3.4
            - uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14.18.3
                  registry-url: 'https://npm.pkg.github.com'
            - run: npm i
            - run: npm version --no-git-tag-version 0.0.0-$VERSION
            - run: npm publish --tag prerelease
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
